# Generated by Django 5.0.2 on 2024-02-25 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bibliothecaire', '0002_media_rename_titre_livre_nom_remove_livre_auteur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nb_emprunts', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_bibliothecaire.membre'),
        ),
        migrations.DeleteModel(
            name='Livre',
        ),
    ]
