# Generated by Django 5.0.2 on 2024-02-25 16:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bibliothecaire', '0003_membre_media_disponible_alter_emprunt_membre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='disponible',
        ),
        migrations.CreateModel(
            name='JeuDePlateau',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_bibliothecaire.media')),
                ('createur', models.CharField(max_length=100)),
            ],
            bases=('gestion_bibliothecaire.media',),
        ),
        migrations.RemoveField(
            model_name='membre',
            name='nb_emprunts',
        ),
        migrations.AddField(
            model_name='membre',
            name='emprunts',
            field=models.ManyToManyField(through='gestion_bibliothecaire.Emprunt', to='gestion_bibliothecaire.media'),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_emprunt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='CD',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_bibliothecaire.media')),
                ('artiste', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True)),
            ],
            bases=('gestion_bibliothecaire.media',),
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_bibliothecaire.media')),
                ('realisateur', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True)),
            ],
            bases=('gestion_bibliothecaire.media',),
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_bibliothecaire.media')),
                ('auteur', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True)),
            ],
            bases=('gestion_bibliothecaire.media',),
        ),
    ]
