# Generated by Django 5.0.2 on 2024-02-25 22:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bibliothecaire', '0004_remove_media_disponible_jeudeplateau_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='emprunts',
        ),
        migrations.AddField(
            model_name='cd',
            name='date_emprunt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dvd',
            name='date_emprunt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jeudeplateau',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='livre',
            name='date_emprunt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
