# Generated by Django 5.0.2 on 2024-02-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bibliothecaire', '0005_remove_membre_emprunts_cd_date_emprunt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cd',
            name='date_emprunt',
        ),
        migrations.RemoveField(
            model_name='cd',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='date_emprunt',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='jeudeplateau',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='date_emprunt',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='media',
            name='titre',
        ),
        migrations.AddField(
            model_name='media',
            name='date_emprunt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='media',
            name='name',
            field=models.CharField(default='kanthio', max_length=100),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_emprunt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
