# Generated by Django 5.0.2 on 2024-02-27 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bibliothecaire', '0006_remove_cd_date_emprunt_remove_cd_disponible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='date_emprunt',
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_emprunt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
