# Generated by Django 5.0.2 on 2024-02-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bibliothecaire', '0007_remove_media_date_emprunt_alter_emprunt_date_emprunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='auteur',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
