# Generated by Django 5.0.2 on 2024-02-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bibliothecaire', '0008_membre_auteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='auteur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
