# Generated by Django 5.0.2 on 2024-02-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bibliothecaire', '0010_alter_membre_auteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('bloque', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='media_ptr',
        ),
        migrations.RemoveField(
            model_name='jeudeplateau',
            name='media_ptr',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='media_ptr',
        ),
        migrations.DeleteModel(
            name='CD',
        ),
        migrations.DeleteModel(
            name='DVD',
        ),
        migrations.DeleteModel(
            name='JeuDePlateau',
        ),
        migrations.DeleteModel(
            name='Livre',
        ),
    ]
