# Generated by Django 5.0.2 on 2024-03-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bibliothecaire', '0013_alter_jeudeplateau_createur_cd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='media',
        ),
        migrations.RemoveField(
            model_name='emprunt',
            name='membre',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='auteur',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Emprunt',
        ),
    ]
