# Generated by Django 5.0.2 on 2024-03-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bibliothecaire', '0014_remove_emprunt_media_remove_emprunt_membre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='bloque',
            field=models.BooleanField(default=False),
        ),
    ]
