# Generated by Django 5.0.2 on 2024-03-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bibliothecaire', '0015_membre_bloque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='bloque',
        ),
        migrations.AddField(
            model_name='emprunteur',
            name='en_retard',
            field=models.BooleanField(default=False),
        ),
    ]
