# Generated by Django 5.0.2 on 2024-03-03 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bibliothecaire', '0018_remove_membre_bloque_membre_emprunteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='emprunteur',
        ),
    ]
