# Generated by Django 5.0.2 on 2024-03-03 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bibliothecaire', '0020_emprunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='cd_emprunte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_bibliothecaire.cd'),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='dvd_emprunte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_bibliothecaire.dvd'),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='livre_emprunte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_bibliothecaire.livre'),
        ),
    ]
