# Generated by Django 5.0.2 on 2024-03-03 18:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bibliothecaire', '0021_emprunt_cd_emprunte_emprunt_dvd_emprunte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_emprunt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_retour',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
